### ISSUE TITLE
Are we support the wasm platform yet?

### ISSUE THREAD

**Issue by driftluo** [nervosnetwork/tentacle#270]
### Runtime compatible

- [x] yamux timer (#268 )
- [x] tentacle timer and spawn(#269 )

### Browser compatible

- [x] websocket abstract encapsulation(#274 )

##### Essential

- [x] Secp256k1(#273 )
- [x] Other hash algorithms, such as sha256 etc..(#273 )
- [x] Hmac Sha256/Sha512(#273 )

##### Optional priority support for one of the major categories

- [ ] ECDH private key negotiation
- - [ ] EcdhP256
- - [ ] EcdhP384
- - [x] X25519(maybe we should add support for this algorithm)(#273 #271 )
- [ ] AEAD symmetric encryption algorithm
- - [ ] Aes128Gcm
- - [ ] Aes256Gcm
- - [x] ChaCha20Poly1305(#273 )

**Comment by driftluo** [comment]
Although we have not implemented all algorithm support on the wasm platform so far, it can already work under the combination of x25519 + chacha20ploy1305. The subsequent support for other algorithms is already another problem, which means that tentacle is currently Can already run on the browser.

For the implementation of other aead algorithms, we should pay attention to this [library](https://github.com/shadowsocks/crypto), which will be used in the [shadowsocks-rust](https://github.com/shadowsocks/shadowsocks-rust) in the near future

For the ecdh algorithm, for now, I don’t know which implementation I should focus on.
